import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import AppShell from "../components/layout/AppShell";
import Breadcrumb from "../components/layout/Breadcrumb";
import EmpleadoForm from "../components/empleados/EmpleadoForm";
import { crearEmpleado, guardarAfiliacion, listarEmpleados } from "../services/empleadosService";
import { listarSupervisores } from "../services/proyectosService";
import { listarUsuarios, nombreUsuario, type UsuarioPublic } from "../services/usuariosService";
import "../styles/AgregarEmpleados.css";

export default function AgregarEmpleados() {
  const navigate=useNavigate(); const [searchParams]=useSearchParams(); const preselectUsuario=searchParams.get("id_usuario")||"";
  const [loading,setLoading]=useState(false), [cargandoCatalogos,setCargandoCatalogos]=useState(true), [error,setError]=useState("");
  const [usuarios,setUsuarios]=useState<UsuarioPublic[]>([]);
  const [supervisores,setSupervisores]=useState<{id_supervisor:number;numero_tarjeta_profesional:string}[]>([]);
  const [idsUsuarioConEmpleado,setIdsUsuarioConEmpleado]=useState<Set<number>>(new Set());
  const [idUsuario,setIdUsuario]=useState(preselectUsuario), [tipoDocumento,setTipoDocumento]=useState("CC"), [numeroDocumento,setNumeroDocumento]=useState(""), [fechaNacimiento,setFechaNacimiento]=useState("");
  const [calle,setCalle]=useState(""), [barrio,setBarrio]=useState(""), [ciudad,setCiudad]=useState(""), [telefono,setTelefono]=useState(""), [correoPersonal,setCorreoPersonal]=useState("");
  const [cargo,setCargo]=useState(""), [fechaIngreso,setFechaIngreso]=useState(""), [salario,setSalario]=useState(""), [formaPago,setFormaPago]=useState("TRANSFERENCIA"), [banco,setBanco]=useState(""), [numeroCuenta,setNumeroCuenta]=useState(""), [idSupervisor,setIdSupervisor]=useState("");
  const [eps,setEps]=useState("Nueva EPS"), [fondoPension,setFondoPension]=useState("Porvenir"), [arl,setArl]=useState("Positiva ARL"), [caja,setCaja]=useState("Compensar"), [nivelArl,setNivelArl]=useState("1");

  useEffect(()=>{if(preselectUsuario)setIdUsuario(preselectUsuario)},[preselectUsuario]);
  useEffect(()=>{(async()=>{try{setCargandoCatalogos(true);setError("");const [us,sups,emps]=await Promise.all([listarUsuarios({limit:200}),listarSupervisores().catch(()=>[]),listarEmpleados().catch(()=>[])]);setUsuarios(us);setSupervisores(Array.isArray(sups)?sups:[]);setIdsUsuarioConEmpleado(new Set((emps||[]).map(e=>Number(e.id_usuario)).filter(Boolean)));}catch(err:unknown){setError(err instanceof Error?err.message:"No se pudieron cargar usuarios. ¿Sesión ADMIN_RRHH?")}finally{setCargandoCatalogos(false)}})()},[]);
  const usuariosDisponibles=useMemo(()=>usuarios.filter(u=>preselectUsuario&&String(u.id_usuario)===String(preselectUsuario)||!idsUsuarioConEmpleado.has(Number(u.id_usuario))),[usuarios,idsUsuarioConEmpleado,preselectUsuario]);
  const usuarioSeleccionado=usuarios.find(u=>String(u.id_usuario)===String(idUsuario));
  const handleGuardar=async()=>{setError("");const faltantes:string[]=[];if(!idUsuario)faltantes.push("Usuario del sistema");if(!numeroDocumento.trim())faltantes.push("Número de documento");if(!fechaNacimiento)faltantes.push("Fecha de nacimiento");if(!calle.trim())faltantes.push("Calle");if(!ciudad.trim())faltantes.push("Ciudad");if(!telefono.trim())faltantes.push("Teléfono");if(!cargo.trim())faltantes.push("Cargo");if(!fechaIngreso)faltantes.push("Fecha de ingreso");if(!salario||Number(salario)<0)faltantes.push("Salario");if(faltantes.length){setError(`Faltan campos obligatorios: ${faltantes.join(", ")}`);return}try{setLoading(true);const empleado=await crearEmpleado({id_usuario:Number(idUsuario),id_supervisor:idSupervisor?Number(idSupervisor):null,tipo_documento:tipoDocumento,numero_documento:numeroDocumento.trim(),fecha_nacimiento:fechaNacimiento,calle:calle.trim(),barrio:barrio.trim()||null,ciudad:ciudad.trim(),telefono:telefono.trim(),correo_personal:correoPersonal.trim()||null,cargo:cargo.trim(),fecha_ingreso:fechaIngreso,salario:Number(salario),forma_pago:formaPago,banco:banco.trim()||null,numero_cuenta:numeroCuenta.trim()||null,estado_laboral:"ACTIVO"});try{if(eps&&fondoPension&&arl&&caja)await guardarAfiliacion(empleado.id_empleado,{eps,fondo_pension:fondoPension,arl,caja_compensacion:caja,nivel_riesgo_arl:Number(nivelArl),estado_afiliacion:"ACTIVO"})}catch{}alert(`Perfil guardado. ID empleado (auto): ${empleado.id_empleado}`+(usuarioSeleccionado?`\nNombre: ${nombreUsuario(usuarioSeleccionado)}`:""));navigate("/empleados")}catch(err:unknown){setError(err instanceof Error?err.message:"No se pudo guardar el empleado")}finally{setLoading(false)}};
  return <AppShell><Breadcrumb items={[{label:"Empleados",to:"/empleados"},{label:"1. Cuenta",to:"/empleados/registrar"},{label:"2. Perfil laboral"}]}/><div className="page-card"><h2 className="page-title">Paso 2 — Perfil laboral del empleado</h2><p className="page-subtitle">El <strong>id_empleado</strong> lo genera la base de datos al guardar (no se escribe). Eliges el <strong>usuario del sistema</strong> por nombre, no un ID a mano.</p>{error&&<div style={{marginBottom:16,color:"#b00020",fontSize:14}}>{error}</div>}{cargandoCatalogos&&<p>Cargando usuarios…</p>}<EmpleadoForm {...{idUsuario,setIdUsuario,tipoDocumento,setTipoDocumento,numeroDocumento,setNumeroDocumento,fechaNacimiento,setFechaNacimiento,calle,setCalle,barrio,setBarrio,ciudad,setCiudad,telefono,setTelefono,correoPersonal,setCorreoPersonal,cargo,setCargo,fechaIngreso,setFechaIngreso,salario,setSalario,formaPago,setFormaPago,banco,setBanco,numeroCuenta,setNumeroCuenta,idSupervisor,setIdSupervisor,eps,setEps,fondoPension,setFondoPension,arl,setArl,caja,setCaja,nivelArl,setNivelArl,usuarios,usuariosDisponibles,supervisores,cargandoCatalogos}}/><div className="agregar-botones" style={{marginTop:20}}><Link to="/empleados/registrar" className="agregar-btn-secundario" style={{textDecoration:"none"}}>← Paso 1 (cuenta)</Link><button className="agregar-btn-primario" type="button" onClick={handleGuardar} disabled={loading||cargandoCatalogos}>{loading?"Guardando…":"Guardar perfil laboral"}</button></div></div></AppShell>;
}
