import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AppShell from "../components/layout/AppShell";
import Breadcrumb from "../components/layout/Breadcrumb";
import EmpleadoEditForm from "../components/empleados/EmpleadoEditForm";
import { obtenerEmpleado, actualizarEmpleado, type Empleado } from "../services/empleadosService";
import "../styles/AgregarEmpleados.css";

export default function EditarEmpleado(){const {id}=useParams<{id:string}>();const navigate=useNavigate();const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[emp,setEmp]=useState<Empleado|null>(null);
const [tipoDocumento,setTipoDocumento]=useState("CC"),[numeroDocumento,setNumeroDocumento]=useState(""),[fechaNacimiento,setFechaNacimiento]=useState(""),[calle,setCalle]=useState(""),[barrio,setBarrio]=useState(""),[ciudad,setCiudad]=useState(""),[telefono,setTelefono]=useState(""),[correoPersonal,setCorreoPersonal]=useState(""),[cargo,setCargo]=useState(""),[fechaIngreso,setFechaIngreso]=useState(""),[salario,setSalario]=useState(""),[formaPago,setFormaPago]=useState("TRANSFERENCIA"),[banco,setBanco]=useState(""),[numeroCuenta,setNumeroCuenta]=useState(""),[estadoLaboral,setEstadoLaboral]=useState("ACTIVO"),[idSupervisor,setIdSupervisor]=useState("");
useEffect(()=>{const idNum=Number(id);if(!idNum){setError("ID de empleado inválido");setLoading(false);return}(async()=>{try{setLoading(true);const e=await obtenerEmpleado(idNum);setEmp(e);setTipoDocumento(e.tipo_documento||"CC");setNumeroDocumento(e.numero_documento||"");setFechaNacimiento((e.fecha_nacimiento||"").slice(0,10));setCalle(e.calle||"");setBarrio(e.barrio||"");setCiudad(e.ciudad||"");setTelefono(e.telefono||"");setCorreoPersonal(e.correo_personal||"");setCargo(e.cargo||"");setFechaIngreso((e.fecha_ingreso||"").slice(0,10));setSalario(String(e.salario??""));setFormaPago(e.forma_pago||"TRANSFERENCIA");setBanco(e.banco||"");setNumeroCuenta(e.numero_cuenta||"");setEstadoLaboral(e.estado_laboral||"ACTIVO");setIdSupervisor(e.id_supervisor!=null?String(e.id_supervisor):"")}catch(err:unknown){setError(err instanceof Error?err.message:"No se pudo cargar el empleado")}finally{setLoading(false)}})()},[id]);
const guardar=async()=>{if(!emp)return;if(!numeroDocumento||!cargo||!ciudad||!telefono||!salario){setError("Completa documento, cargo, ciudad, teléfono y salario.");return}try{setSaving(true);setError("");setOk("");await actualizarEmpleado(emp.id_empleado,{tipo_documento:tipoDocumento,numero_documento:numeroDocumento.trim(),fecha_nacimiento:fechaNacimiento||undefined,calle:calle.trim(),barrio:barrio.trim()||null,ciudad:ciudad.trim(),telefono:telefono.trim(),correo_personal:correoPersonal.trim()||null,cargo:cargo.trim(),fecha_ingreso:fechaIngreso||undefined,salario:Number(salario),forma_pago:formaPago,banco:banco.trim()||null,numero_cuenta:numeroCuenta.trim()||null,estado_laboral:estadoLaboral,id_supervisor:idSupervisor?Number(idSupervisor):null});setOk("Empleado actualizado correctamente.")}catch(err:unknown){setError(err instanceof Error?err.message:"No se pudo actualizar")}finally{setSaving(false)}};
return <AppShell><Breadcrumb items={[{label:"Empleados",to:"/empleados"},{label:`Editar #${id}`}]}/><div className="page-card"><h1 className="page-title">Editar empleado</h1><p className="page-subtitle">PATCH /empleados/&#123;id&#125; — no es el formulario de alta.</p>{loading&&<p>Cargando…</p>}{error&&<p style={{color:"#b00020"}}>{error}</p>}{ok&&<p style={{color:"#047857"}}>{ok}</p>}{!loading&&emp&&<><EmpleadoEditForm {...{tipoDocumento,setTipoDocumento,numeroDocumento,setNumeroDocumento,fechaNacimiento,setFechaNacimiento,calle,setCalle,barrio,setBarrio,ciudad,setCiudad,telefono,setTelefono,correoPersonal,setCorreoPersonal,cargo,setCargo,fechaIngreso,setFechaIngreso,salario,setSalario,formaPago,setFormaPago,banco,setBanco,numeroCuenta,setNumeroCuenta,estadoLaboral,setEstadoLaboral,idSupervisor,setIdSupervisor}}/><div className="agregar-botones" style={{marginTop:20}}><button className="agregar-btn-secundario" type="button" onClick={()=>navigate("/empleados")}>Volver a lista</button><button className="agregar-btn-primario" type="button" onClick={guardar} disabled={saving}>{saving?"Guardando…":"Guardar cambios"}</button></div></>}</div></AppShell>}
